name: "Nix Image"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types: [ "created" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: nix build -L .#nixosConfigurations.iso.config.system.build.isoImage
    - name: Upload iso
      uses: actions/upload-artifact@v4
      with:
        name: nixos-usb-installer
        path: result/iso/*.iso
        retention-days: 1
    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      if: github.event_name == 'release' && github.event.action == 'created'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_paths: '["result/iso/*.iso"]'
    
    - name: ZeroTier
      uses: zerotier/github-action@v1.0.1
      with:
        network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
        auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
        api_url: ${{ secrets.ZEROTIER_API_URL }}
    - name: Minio Deploy
      uses: hkdobrev/minio-deploy-action@v1
      with:
        endpoint: ${{ secrets.MINIO_ENDPOINT }}
        access_key: ${{ secrets.MINIO_ACCESS_KEY }}
        secret_key: ${{ secrets.MINIO_SECRET_KEY }}
        bucket: 'linux-images'
        source_dir: 'result/iso/*.iso'
        target_dir: '/tfc-nix/'
